apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-demo-app
  template:
    metadata:
      labels:
        app: platform-demo-app
    spec:
      containers:
      - name: platform-demo-app
        image: 656732270566.dkr.ecr.us-east-1.amazonaws.com/platform-demo-app:latest
        ports:
        - containerPort: 5000